<h2>Form Validation</h2>
<!-- error handling -->

<!-- 
    Error Handling Explanation:

    - $errors->any()  
      Checks if there are any validation errors present (returns true if there are errors). 
      Used in an @@if directive to conditionally display the block for error output.

    - $errors->all()  
      Returns an array of all error messages generated by the validator.
      Used in a @@foreach loop to display each error message to the user.

    - @@error('field')  
      Blade directive that checks for a validation error related to a specific input field.
      Typically placed directly below each field to show field-specific error messages.
-->


<!-- this will if and for loop errors will be displayed above the form -->
@if($errors->any())
@foreach($errors->all() as $error)
<p style="color: red;">{{ $error }}</p>
@endforeach

@endif
<form action="/validate-form" method="post">
    @csrf
    <div>
        <label for="name">Name</label>
        <input type="text" name="name" id="name"/>
        @error('name')
        <p style="color: red;">{{ $message }}</p>
        @enderror
    </div>
    <div>
        <label for="email">Email</label>
        <input type="email" name="email" id="email"/>
        <!-- this will display the error message for the email field -->
        @error('email')
        <p style="color: red;">{{ $message }}</p>
        @enderror
    </div>
    <div>
        <label for="password">Password</label>
        <input type="password" name="password" id="password"/>
        @error('password')
        <p style="color: red;">{{ $message }}</p>
        @enderror
    </div>
    <div>
        <label for="confirm_password">Confirm Password</label>
        <input type="password" name="confirm_password" id="confirm_password"/>
        @error('confirm_password')
        <p style="color: red;">{{ $message }}</p>
        @enderror
    </div>
    <button type="submit">Submit</button>
</form>

<style>
    div {
        margin: 10px;
    }
    label {
        display: block;
        margin-bottom: 5px;
    }
    input {
        padding: 5px;
        border: 1px solid #ccc;
        border-radius: 5px;
    }
    button {
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
    }
</style>