<h2>Form Validation</h2>
<!-- error handling -->

<!-- 
    Error Handling Explanation:

    - $errors->any()  
      Checks if there are any validation errors present (returns true if there are errors). 
      Used in an @@if directive to conditionally display the block for error output.

    - $errors->all()  
      Returns an array of all error messages generated by the validator.
      Used in a @@foreach loop to display each error message to the user.

    - @@error('field')  
      Blade directive that checks for a validation error related to a specific input field.
      Typically placed directly below each field to show field-specific error messages.
-->


<!-- this will if and for loop errors will be displayed above the form -->
@if($errors->any())
@foreach($errors->all() as $error)
<p style="color: red;">{{ $error }}</p>
@endforeach

@endif
<form action="/validate-form" method="post">
    @csrf
    <div>
        <label for="name">Name</label>
        <!-- 
            The value="{{ old('name') }}" attribute:
                - Displays the previously entered value in the 'name' field if the form is reloaded after validation fails.
                - Keeps user input intact so users don't have to retype data after a failed submission.

            The class="{{ $errors->has('name') ? 'input-error' : '' }}":
                - Dynamically adds the "input-error" CSS class to the input field if there is a validation error for 'name'.
                - $errors->has('name') is a Laravel helper that returns true if there is a validation error for the 'name' field.
                - we can also use the $errors->first('name') to get the first error message for the 'name' field
            Summary:
                - Together, these features improve the user experience by both highlighting invalid fields and preserving user input after an error.
        -->
   

        <input type="text" name="name" id="name" value="{{ old('name') }}" class="{{ $errors->has('name') ? 'input-error' : '' }}" />
        @error('name')
        <p style="color: red;">{{ $message }}</p>
        @enderror
    </div>
    <div>
        <label for="email">Email</label>
        <input type="email" name="email" id="email" value="{{ old('email') }}" />
        <!-- this will display the error message for the email field -->
        @error('email')
        <p style="color: red;">{{ $message }}</p>
        @enderror
    </div>
    <div>
        <label for="password">Password</label>
        <input type="password" name="password" id="password" value="{{ old('password') }}" />
        @error('password')
        <p style="color: red;">{{ $message }}</p>
        @enderror
    </div>
    <div>
        <label for="confirm_password">Confirm Password</label>
        <input type="password" name="confirm_password" id="confirm_password"/>
        @error('confirm_password')
        <p style="color: red;">{{ $message }}</p>
        @enderror
    </div>
    <button type="submit">Submit</button>
</form>

<style>
    div {
        margin: 10px;
    }
    label {
        display: block;
        margin-bottom: 5px;
    }
    input {
        padding: 5px;
        border: 1px solid #ccc;
        border-radius: 5px;
    }
    button {
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
    }
    .input-error {
        border: 1px solid red;
        color: red;
    }
</style>